backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Add to featured", name: "featured", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - label: "Pages"
    name: "pages"
    files: 
      - label: "About Page"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Update Date", name: "date", widget: "datetime"}
          - {label: "Facebook", name: "facebook", widget: "string", required: false}
          - {label: "Twitter", name: "twitter", widget: "string", required: false}
          - {label: "Linkedin", name: "linkedin", widget: "string", required: false}
          - {label: "Instagram", name: "facebook", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Categories Page"
        name: "categories"
        file: "src/content/pages/categories.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "categories"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Update Date", name: "date", widget: "datetime"}
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
      - label: "Authors"
        name: "authors"
        file: "src/content/pages/authors.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "authors"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Update Date", name: "date", widget: "datetime"}
          - label: "Authors"
            name: "authors"
            widget: "list"
            fields:
              - {label: "Names", name: "names", widget: "string"}
              - {label: "Bio", name: "bio", widget: "string"}
              - {label: "Twitter", name: "twitter", widget: "string", required: false}
              - {label: "Linkedin", name: "linkedin", widget: "string", required: false}
              - {label: "Image", name: "image", widget: "image"}
